---
# Service for data from prometheus exporters for nginx ingress
apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus
spec:
  selector:
    prometheus: nginx-prometheus
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  type: NodePort
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: nginx-prometheus
spec:
  scrapeInterval: "5s"
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: prometheus-monitor
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx
  labels:
    app: prometheus-monitor
spec:
  endpoints:
  - interval: 30s
    targetPort: 10254
#    port: metrics
    path: "/metrics"
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  namespaceSelector:
    matchNames:
    - ingress-nginx
